const Events = [
    {
        key: 0,
        Day: 0,
        Title: "Podstawy inżynerii oprogramowania",
        Place: "i24 B19 403",
        Lektor: "Kowalski J",
        From: 12,
        To: 14,
        Type: "l",
    },

    {
        key: 1,
        Day: 3,
        Title: "Systemy wbudowane",
        Place: "k22 B18 I.M",
        Lektor: "Kowalski J",
        From: 8,
        To: 11,
        Type: "l",
    },

    {
        key: 2,
        Day: 0,
        Title: "Jezyk Obcy",
        Place: "_B24",
        Lektor: "Kowalski J",
        From: 8,
        To: 10,
        Type: "lekt",
    },

    {
        key: 3,
        Day: 1,
        Title: "Bazy Danych",
        Place: "E2",
        Lektor: "Kowalski J",
        From: 10,
        To: 12,
        Type: "w",
    },
    {
        key: 4,
        Day: 1,
        Title: "Komunikacja człowiek-komputer",
        Place: "E2",
        Lektor: "Kowalski J",
        From: 12,
        To: 14,
        Type: "w",
    },
    {
        key: 5,
        Day: 1,
        Title: "Podstawy inżynerii oprogramowania",
        Place: "E2",
        Lektor: "Kowalski J",
        From: 14,
        To: 16,
        Type: "w",
    },
    {
        key: 6,
        Day: 1,
        Title: "Programowanie obiektowe || (Java)",
        Place: "Zdalnie",
        Lektor: "Kowalski J",
        From: 17,
        To: 19,
        Type: "w",
    },
    {
        key: 7,
        Day: 2,
        Title: "Automatyzacja obliczeń inżynierskich",
        Place: "i24 E110",
        Lektor: "Kowalski J",
        From: 10,
        To: 12,
        Type: "l",
    },
    {
        key: 8,
        Day: 2,
        Title: "Komunikacja człowiek-komputer",
        Place: "i24 E110",
        Lektor: "Kowalski J",
        From: 12,
        To: 14,
        Type: "p",
    },
    {
        key: 9,
        Day: 3,
        Title: "Bazy Danych",
        Place: "i25 IBM",
        Lektor: "Kowalski J",
        From: 12,
        To: 14,
        Type: "l",
    },
    {
        key: 10,
        Day: 3,
        Title: "Programowanie obiektowe || (Java)",
        Place: "k22 B18 I.C",
        Lektor: "Kowalski J",
        From: 14,
        To: 16,
        Type: "l",
    },
    {
        key: 11,
        Day: 4,
        Title: "Systemy wbudowane",
        Place: "k22 B18 A2",
        Lektor: "Kowalski J",
        From: 8,
        To: 10,
        Type: "w",
    },
    {
        key: 12,
        Day: 4,
        Title: "Sieci komputerowe",
        Place: "E1",
        Lektor: "Kowalski J",
        From: 10,
        To: 12,
        Type: "w",
    },
    {
        key: 13,
        Day: 4,
        Title: "Automatyzacja obliczeń inżynierskich",
        Place: "E2",
        Lektor: "Kowalski J",
        From: 14,
        To: 16,
        Type: "w",
    },
    {
        key: 14,
        Day: 4,
        Title: "Sieci komputerowe",
        Place: "i24 311",
        Lektor: "Kowalski J",
        From: 16,
        To: 18,
        Type: "l",
    },
]

module.exports = Events;